title: Site
# preset: pages
unlisted: true

columns:
  # main
  main:
    sections:
      pages:
        type: pages
        headline: Pages
        type: pages
        headline: Subpages
        create: project # new pages can only be created with the default template